apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-clusterrole
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "services", "pods"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
